title: NLP Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to NLP conference deadlines
author: Go Inoue

url: "https://go-inoue.github.io/camel-deadlines/index.html"
baseurl: "https://go-inoue.github.io/camel-deadlines"

twitter_username: ""
twitter_hashtag: ""
github_username: go-inoue
github_repo: camel-deadlines

markdown: kramdown
ga_id: UA-36274081-2
